# Generated by Django 2.2.5 on 2020-06-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_subscription_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
