# Generated by Django 2.2.5 on 2020-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20200609_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='amount_of_subscription_emails',
            field=models.IntegerField(default=0),
        ),
    ]
