# Generated by Django 2.2.5 on 2020-06-09 21:44

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20200609_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_subscription_email_date',
            field=models.DateTimeField(blank=True, default=authentication.utils.get_current_time, null=True),
        ),
    ]
