# Generated by Django 2.2.5 on 2020-06-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20200609_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
    ]
