# Generated by Django 2.2.5 on 2020-02-22 16:57

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('device_brand', models.CharField(default=None, max_length=200)),
                ('os_system', models.CharField(default=None, max_length=200)),
                ('disconnected_date', models.DateTimeField(default=authentication.utils.get_current_time)),
                ('connected_date', models.DateTimeField(default=authentication.utils.get_current_time)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
