# Generated by Django 2.2.5 on 2020-05-30 17:50

import authentication.utils
import buy_ticket.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_crud', '0011_auto_20200530_1750'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(default=buy_ticket.utils.id_generator, unique=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('additional_info', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=authentication.utils.get_current_time)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_crud.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
