# Generated by Django 2.2.5 on 2020-06-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy_ticket', '0002_auto_20200531_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.IntegerField(choices=[(0, 'BUY_TICKET'), (1, 'PAY_FREE_EVENT')], default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
