# Generated by Django 2.2.5 on 2020-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0003_auto_20200601_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
