# Generated by Django 2.2.5 on 2020-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0004_ticket_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
