# Generated by Django 2.2.5 on 2020-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0006_auto_20200606_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reason',
            field=models.IntegerField(choices=[(0, 'BUY_TICKET'), (1, 'PAY_FOR_FREE_EVENT')], default=0),
        ),
    ]
