# Generated by Django 2.2.5 on 2020-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_ticket', '0007_auto_20200606_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
