# Generated by Django 2.2.5 on 2020-03-03 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
