# Generated by Django 2.2.5 on 2020-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0002_event_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_phone_number',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
