# Generated by Django 2.2.5 on 2020-04-18 12:21

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0003_auto_20200416_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=authentication.utils.get_current_time),
        ),
    ]
