# Generated by Django 2.2.5 on 2020-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0004_auto_20200418_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_ticket_fee',
            field=models.IntegerField(default=0),
        ),
    ]
