# Generated by Django 2.2.5 on 2020-04-18 13:24

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0005_auto_20200418_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=authentication.utils.get_current_time),
        ),
    ]
