# Generated by Django 2.2.5 on 2020-06-02 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0014_auto_20200601_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 10, 26, 17, 594561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 10, 26, 17, 594509, tzinfo=utc)),
        ),
    ]
