# Generated by Django 2.2.5 on 2020-06-06 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0018_auto_20200606_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_refunded_to_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 19, 39, 49, 601201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 19, 39, 49, 601139, tzinfo=utc)),
        ),
    ]
