# Generated by Django 2.2.5 on 2020-06-08 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0021_auto_20200608_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_user_payments_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 43, 30, 986017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 43, 30, 985992, tzinfo=utc)),
        ),
    ]
