# Generated by Django 2.2.5 on 2020-06-14 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_crud', '0027_auto_20200610_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 10, 30, 56, 261846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 10, 30, 56, 261818, tzinfo=utc)),
        ),
    ]
