# Generated by Django 2.2.5 on 2020-02-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0004_auto_20200224_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
