# Generated by Django 2.2.5 on 2020-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0005_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
