# Generated by Django 2.2.5 on 2020-03-26 12:12

from django.db import migrations, models
import user_crud.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0006_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ot_token',
            field=models.IntegerField(default=user_crud.models.generate_int_token, unique=True),
        ),
    ]
