# Generated by Django 2.2.5 on 2020-03-26 12:13

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0007_customuser_ot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ot_token_date',
            field=models.DateTimeField(default=authentication.utils.get_current_time),
        ),
    ]
