# Generated by Django 2.2.5 on 2020-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0008_customuser_ot_token_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
