# Generated by Django 2.2.5 on 2020-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0009_customuser_reset_password_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
