# Generated by Django 2.2.5 on 2020-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0011_remove_address_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, to='user_crud.Category'),
        ),
    ]
