# Generated by Django 2.2.5 on 2020-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0012_auto_20200424_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
