# Generated by Django 2.2.5 on 2020-06-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0014_customuser_stripe_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
