# Generated by Django 2.2.5 on 2020-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0015_delete_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
